version: '3.8'
services:
  redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"

  postgres-db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12070107Don
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: todoapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/postgres?currentSchema=todo-app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12070107Don
    depends_on:
      - postgres-db
      - redis
    ports:
      - "8080:8080"

  flyway:
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://postgres-db:5432/postgres -schemas=todo-app -user=postgres -password=12070107Don migrate
    depends_on:
      - postgres-db
