version: '3.8'
services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12070107Don
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: todoapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12070107Don
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
