server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=todo-app
    username: postgres
    password: 12070107Don
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
        envers:
          autoRegisterListeners: true
          store_data_at_delete: true
          audit_table_suffix: _history
          revision_field_name: revision
          revision_type_field_name: revision_type
    flyway:
      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=todo-app
      user: postgres
      password: 12070107Don
      locations: classpath:db/migration
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis


jwt:
  secret: ${JWT_SECRET:7x4hB2vT9qYpXwLcRfUjMnZk6tAeDgHsKbP3yV5N8WmQrJdFt0z1C}
  expiration: 86400000
  refresh-expiration: 604800000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    kz.don.todo_app: TRACE
    org.hibernate: DEBUG